# Generated by Django 2.1.5 on 2019-03-09 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cimdi', (('darba_cimdi', 'Darba cimdi'), ('ziemas_cimdi', 'Ziemas cimdi'))), ('Bikses', (('vasaras_bikses', 'Vasaras bikses'), ('ziemas_bikses', 'Ziemas bikses'))), ('Zabaki', (('siltie', 'siltie'), ('armijas', 'armijas')))], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
