# Generated by Django 2.1.5 on 2019-03-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190309_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cimdi', (('darba_cimdi', 'Darba cimdi'), ('ziemas_cimdi', 'Ziemas cimdi'))), ('Bikses', (('vasaras_bikses', 'Vasaras bikses'), ('ziemas_bikses', 'Ziemas bikses'))), ('Zabaki', (('siltie', 'siltie'), ('armijas', 'armijas')))], max_length=10),
        ),
    ]
