# Generated by Django 2.1.5 on 2019-03-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190309_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category',
        ),
    ]
