# Generated by Django 2.1.5 on 2019-03-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190309_1544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='size',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='size',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
