# Generated by Django 2.1.5 on 2019-03-09 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190309_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizetype',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='sizeType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.SizeType'),
        ),
    ]
