# Generated by Django 2.1.5 on 2019-03-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190309_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='sizeType',
        ),
        migrations.AddField(
            model_name='sizetype',
            name='size',
            field=models.ManyToManyField(blank=True, to='products.Size'),
        ),
    ]
